version: '3'

services:
  pure-data:
    build: .
    volumes:
      - "./pure-data-patches:/root/pure-data-patches"
      - "./recordings:/root/recordings"
    command: pd -nogui pure-data-patches/main.pd